version: '3'

services:
  db:
    image: postgres
    env_file:
      .env
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "db"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
